//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValenceDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContactDetail
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string First_Name { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Last_Name { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public decimal Phone_No { get; set; }

        public  bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
